export const mockTransactions = [
  { id: '1', amount: 34.50, category: 'Food', merchant: 'Starbucks', date: '2026-03-17' },
  { id: '2', amount: 89.99, category: 'Food', merchant: 'Uber Eats', date: '2026-03-16' },
  { id: '3', amount: 45.00, category: 'Food', merchant: 'Uber Eats', date: '2026-03-15' },
  { id: '4', amount: 12.50, category: 'Transport', merchant: 'Uber', date: '2026-03-17' },
  { id: '5', amount: 8.00, category: 'Transport', merchant: 'Uber', date: '2026-03-16' },
  { id: '6', amount: 15.99, category: 'Entertainment', merchant: 'Netflix', date: '2026-03-15' },
  { id: '7', amount: 9.99, category: 'Entertainment', merchant: 'Spotify', date: '2026-03-14' },
  { id: '8', amount: 67.00, category: 'Shopping', merchant: 'ASOS', date: '2026-03-13' },
  { id: '9', amount: 120.00, category: 'Bills', merchant: 'Electric Bill', date: '2026-03-12' },
  { id: '10', amount: 22.00, category: 'Food', merchant: 'Chipotle', date: '2026-03-11' },
  { id: '11', amount: 55.00, category: 'Food', merchant: 'Whole Foods', date: '2026-03-10' },
  { id: '12', amount: 18.75, category: 'Food', merchant: 'Sweetgreen', date: '2026-03-09' },
  { id: '13', amount: 42.00, category: 'Transport', merchant: 'Lyft', date: '2026-03-08' },
  { id: '14', amount: 6.50, category: 'Transport', merchant: 'Metro Card', date: '2026-03-07' },
  { id: '15', amount: 29.99, category: 'Entertainment', merchant: 'Hulu', date: '2026-03-06' },
  { id: '16', amount: 14.99, category: 'Entertainment', merchant: 'Apple Music', date: '2026-03-05' },
  { id: '17', amount: 85.00, category: 'Shopping', merchant: 'Zara', date: '2026-03-04' },
  { id: '18', amount: 199.00, category: 'Bills', merchant: 'Rent Insurance', date: '2026-03-03' },
  { id: '19', amount: 75.00, category: 'Bills', merchant: 'Internet', date: '2026-03-02' },
  { id: '20', amount: 33.00, category: 'Food', merchant: 'DoorDash', date: '2026-03-01' },
  { id: '21', amount: 27.50, category: 'Food', merchant: 'Panera Bread', date: '2026-02-28' },
  { id: '22', amount: 11.00, category: 'Transport', merchant: 'Uber', date: '2026-02-27' },
  { id: '23', amount: 64.99, category: 'Shopping', merchant: 'Amazon', date: '2026-02-26' },
  { id: '24', amount: 19.99, category: 'Entertainment', merchant: 'HBO Max', date: '2026-02-25' },
  { id: '25', amount: 48.00, category: 'Food', merchant: 'Trader Joes', date: '2026-02-24' },
  { id: '26', amount: 15.00, category: 'Transport', merchant: 'Lyft', date: '2026-02-23' },
  { id: '27', amount: 39.99, category: 'Shopping', merchant: 'Target', date: '2026-02-22' },
  { id: '28', amount: 95.00, category: 'Bills', merchant: 'Phone Bill', date: '2026-02-21' },
  { id: '29', amount: 7.50, category: 'Food', merchant: 'McDonalds', date: '2026-02-20' },
  { id: '30', amount: 125.00, category: 'Shopping', merchant: 'Nike', date: '2026-02-19' },
  { id: '31', amount: 23.00, category: 'Food', merchant: 'Panda Express', date: '2026-02-18' },
  { id: '32', amount: 50.00, category: 'Bills', merchant: 'Gym Membership', date: '2026-02-17' },
];

export const mockChallenges = [
  { id: 'c1', category: 'Food', text: 'You spent $34 on coffee this week. Your challenge: make coffee at home 3 days this week.', context: 'Based on: Starbucks spending this week', type: 'spending' },
  { id: 'c2', category: 'Food', text: 'Uber Eats orders totaled $135 this week. Try cooking at home for dinner tonight.', context: 'Based on: $135 Uber Eats total', type: 'spending' },
  { id: 'c3', category: 'Transport', text: 'You took 4 Uber rides this week. Walk or bike for trips under 1 mile today.', context: 'Based on: 4 ride-hail trips', type: 'spending' },
  { id: 'c4', category: 'Entertainment', text: 'You have 4 streaming subscriptions ($61/mo). Cancel the one you used least this month.', context: 'Based on: Netflix, Spotify, Hulu, Apple Music', type: 'saving' },
  { id: 'c5', category: 'Shopping', text: 'Before your next purchase over $50, wait 48 hours. Still want it? Then buy it.', context: 'Based on: $67 ASOS + $85 Zara', type: 'habit' },
  { id: 'c6', category: 'Food', text: 'Pack lunch for work tomorrow. You spent $22 on Chipotle alone.', context: 'Based on: frequent lunch spending', type: 'spending' },
  { id: 'c7', category: 'Saving', text: 'Move $25 to savings right now. Small deposits compound fast.', context: 'Based on: no savings activity this week', type: 'saving' },
  { id: 'c8', category: 'Bills', text: 'Review your electric bill. Switching to LED bulbs could save $15/month.', context: 'Based on: $120 electric bill', type: 'saving' },
  { id: 'c9', category: 'Food', text: 'Meal prep on Sunday for 3 days this week. Your weekday food spend is 3x your weekend.', context: 'Based on: weekday vs weekend patterns', type: 'habit' },
  { id: 'c10', category: 'Shopping', text: 'Unsubscribe from 3 marketing emails today. Remove the temptation.', context: 'Based on: impulse shopping pattern', type: 'habit' },
  { id: 'c11', category: 'Transport', text: 'Take public transit today instead of rideshare. Save ~$30 this week.', context: 'Based on: $42 Lyft ride', type: 'spending' },
  { id: 'c12', category: 'Food', text: 'Set a $15 lunch budget today. Track every dollar.', context: 'Based on: avg $25 lunch spend', type: 'spending' },
  { id: 'c13', category: 'Entertainment', text: 'Host a movie night at home instead of going out this weekend.', context: 'Based on: entertainment spending trend', type: 'saving' },
  { id: 'c14', category: 'Shopping', text: 'Delete saved payment info from your top 2 shopping apps.', context: 'Based on: impulse purchase history', type: 'habit' },
  { id: 'c15', category: 'Saving', text: 'Set up automatic $50/month transfer to savings. Automate the good habits.', context: 'Based on: inconsistent savings', type: 'saving' },
  { id: 'c16', category: 'Food', text: 'Try a no-spend food day: eat only what you already have at home.', context: 'Based on: daily food spending', type: 'spending' },
  { id: 'c17', category: 'Bills', text: 'Call your internet provider and negotiate a lower rate. Average savings: $20/mo.', context: 'Based on: $75 internet bill', type: 'saving' },
  { id: 'c18', category: 'Transport', text: 'Carpool with a coworker this week. Split costs = instant 50% savings.', context: 'Based on: solo commute spending', type: 'spending' },
  { id: 'c19', category: 'Shopping', text: 'Return one item you bought this month that you haven\'t used yet.', context: 'Based on: recent purchases', type: 'saving' },
  { id: 'c20', category: 'Food', text: 'Replace 2 takeout meals with home-cooked this week. Save ~$40.', context: 'Based on: takeout frequency', type: 'spending' },
  { id: 'c21', category: 'Saving', text: 'Open a high-yield savings account if you don\'t have one. Earn 4%+ APY.', context: 'Based on: savings optimization', type: 'saving' },
  { id: 'c22', category: 'Entertainment', text: 'Use a free alternative today: library, park, or free museum day.', context: 'Based on: entertainment spending', type: 'spending' },
  { id: 'c23', category: 'Bills', text: 'Switch your phone plan to a cheaper option. Compare plans online today.', context: 'Based on: $95 phone bill', type: 'saving' },
  { id: 'c24', category: 'Food', text: 'Buy store brand instead of name brand for your next 3 grocery items.', context: 'Based on: Whole Foods spending', type: 'spending' },
  { id: 'c25', category: 'Shopping', text: 'Implement the "one in, one out" rule: buy something new, donate something old.', context: 'Based on: accumulation pattern', type: 'habit' },
  { id: 'c26', category: 'Transport', text: 'Map out your weekly trips. Can any be combined to save fuel/fares?', context: 'Based on: multiple trips daily', type: 'habit' },
  { id: 'c27', category: 'Saving', text: 'Round up your next 5 purchases and save the difference. ($4.30 → save $0.70)', context: 'Based on: micro-savings opportunity', type: 'habit' },
  { id: 'c28', category: 'Food', text: 'Drink only water today. Skip the $5 lattes and $3 sodas.', context: 'Based on: beverage spending', type: 'spending' },
  { id: 'c29', category: 'Bills', text: 'Review all subscriptions. Cancel anything you haven\'t used in 30 days.', context: 'Based on: subscription audit', type: 'saving' },
  { id: 'c30', category: 'Shopping', text: 'Create a wishlist. Wait 7 days before buying anything on it.', context: 'Based on: impulse buying pattern', type: 'habit' },
];

export const mockUser = {
  name: 'Alex Johnson',
  email: 'alex@example.com',
  subscriptionTier: 'free' as const,
  streak: 12,
  longestStreak: 23,
  completionRate: 78,
};

export const mockBehavioralProfile = {
  spendingAwareness: 65,
  savingReflex: 30,
  debtMindset: 45,
  impulsivity: 70,
  planning: 35,
  consistency: 55,
  primaryPersona: 'The Impulse Buyer',
};

export const mockCompletedChallenges = [
  { id: 'h1', date: '2026-03-17', text: 'Made coffee at home 3 days', category: 'Food', status: 'complete' as const },
  { id: 'h2', date: '2026-03-16', text: 'Took the subway instead of Uber', category: 'Transport', status: 'complete' as const },
  { id: 'h3', date: '2026-03-15', text: 'Cooked dinner at home', category: 'Food', status: 'complete' as const },
  { id: 'h4', date: '2026-03-14', text: 'Cancelled unused Hulu subscription', category: 'Entertainment', status: 'complete' as const },
  { id: 'h5', date: '2026-03-13', text: 'Waited 48hrs before buying shoes', category: 'Shopping', status: 'skip' as const },
  { id: 'h6', date: '2026-03-12', text: 'Packed lunch for work', category: 'Food', status: 'complete' as const },
  { id: 'h7', date: '2026-03-11', text: 'Moved $25 to savings', category: 'Saving', status: 'complete' as const },
  { id: 'h8', date: '2026-03-10', text: 'Switched to LED bulbs', category: 'Bills', status: 'complete' as const },
  { id: 'h9', date: '2026-03-09', text: 'Meal prepped for 3 days', category: 'Food', status: 'complete' as const },
  { id: 'h10', date: '2026-03-08', text: 'Unsubscribed from marketing emails', category: 'Shopping', status: 'skip' as const },
];

export const categoryColors: Record<string, string> = {
  Food: '#E67E22',
  Transport: '#3498DB',
  Entertainment: '#9B59B6',
  Shopping: '#E74C3C',
  Bills: '#1ABC9C',
  Saving: '#1B4332',
};
